apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-k8s
  template:
    metadata:
      labels:
        app: my-app-k8s
    spec:
      containers:
      - name: my-app-container
        image: rohitabraham02/express-kubernetes-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app-k8s
  ports:
   - port: 8080
     targetPort: 8080
