apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  index.html: |
    <html>
    <body>
    <h1>Hello from ConfigMap</h1>
    </body>
    </html>

---
apiVersion: v1
kind: Pod
metadata:
  name: app-with-configmap
spec:
  containers:
  - name: app-container
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: config-name
  volumes:
  - name: config-name
    configMap:
      name: example-config
