apiVersion: v1
kind: Pod
metadata:
  name: app-with-hostpath
spec:
  containers:
  - name: app-container
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-volume
  volumes:
  - name: my-volume
    hostPath:
      path: /data/nginx
      type: Directory
