apiVersion: v1
kind: Pod
metadata:
  name: app1
spec:
  containers:
  - name: app1-container
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-volume
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-pvc
